// The crush bake-off: one line at every crush strength, plus the clean master it was made from, so
// Tim can pick the house level. Nothing here is baked into a recording — the masters in
// assets/voice are read and left alone.
//
//   node tools/voice-crush.mjs <out dir> [<clip name>]   default clip: shot1-ward
//   node tools/voice-crush.mjs --budget                  what the game's speech costs at each level
//   node tools/voice-crush.mjs --bake                    crush the intro masters into the game
//
// --bake is how a master reaches the game: it writes src/snes/audio/intro-brr.mjs, the crushed
// samples the intro plays, at whatever the crush dial is set to. Re-run it after moving the dial;
// no line is ever re-recorded.

import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CRUSH, CRUSH_LEVELS, VOICE_BUDGET, crushBytes, crushLevel, digitize, masterClip, parseWav, renderLine, voiceOf } from '../src/snes/audio/voice.mjs';
import { DSP_HZ } from '../src/snes/audio/spc.mjs';
import { LINES } from '../src/snes/attract.mjs';
import { pack } from './snes-bank.mjs';
import { wav } from './snes-render.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const MASTERS = join(ROOT, 'assets', 'voice', 'intro');

export const masterOf = (clip) => parseWav(readFileSync(join(MASTERS, `${clip}.wav`)));

// Seconds of speech the intro holds, from its own timeline.
export const introSeconds = () => LINES.reduce((n, l) => n + l.s, 0);

// One intro line crushed for the game: the BRR sample, the frames it lasts at the character's pitch.
export function bakeLine(line, at = crushLevel()) {
  const v = voiceOf(line.who, at);
  const s = digitize(line.who, masterOf(line.clip), at);
  return {
    frames: Math.ceil((s.pcm.length / (v.rate * 2 ** (v.pitch / 12))) * 60) + 6,
    rootHz: Number(s.rootHz.toFixed(4)),
    brr: pack(s.brr),
  };
}

function bake() {
  const at = crushLevel();
  const rows = [];
  let bytes = 0;
  for (const line of LINES) {
    const b = bakeLine(line, at);
    bytes += (b.brr.length * 3) / 4;
    rows.push(`  '${line.clip}': { who: '${line.who}', frames: ${b.frames}, rootHz: ${b.rootHz}, brr: '${b.brr}' },`);
    console.log(line.clip.padEnd(18), `${b.frames} frames`);
  }
  const head = `// Generated by tools/voice-crush.mjs --bake: the intro's spoken lines, crushed from the clean\n// masters in assets/voice/intro at the '${at}' setting (${CRUSH[at].rate} Hz). The masters stay full quality and never\n// reach the game; move the dial in src/snes/audio/voice.mjs and re-run to change how this sounds.\n\nexport const CRUSH_AT = '${at}';\n\nexport default {\n`;
  writeFileSync(join(ROOT, 'src', 'snes', 'audio', 'intro-brr.mjs'), `${head}${rows.join('\n')}\n};\n`);
  console.log(`${(bytes / 1024).toFixed(0)} KB of samples, ${((bytes / VOICE_BUDGET) * 100).toFixed(1)}% of the 1 MB budget`);
}

if (process.argv[1]?.endsWith('voice-crush.mjs')) {
  if (process.argv[2] === '--bake') {
    bake();
  } else if (process.argv[2] === '--budget') {
    const s = introSeconds();
    console.log(`${s.toFixed(1)} s of intro speech`);
    for (const at of CRUSH_LEVELS) {
      const bytes = crushBytes(s, at);
      console.log(`  ${at.padEnd(6)} ${String(CRUSH[at].rate).padStart(5)} Hz  ${(bytes / 1024).toFixed(0).padStart(4)} KB  ${((bytes / VOICE_BUDGET) * 100).toFixed(1)}% of the 1 MB budget`);
    }
  } else {
    const out = process.argv[2];
    if (!out) throw new Error('usage: node tools/voice-crush.mjs <out dir> [<clip name>]');
    const clip = process.argv[3] ?? 'shot1-ward';
    const line = LINES.find((l) => l.clip === clip);
    if (!line) throw new Error(`no intro line "${clip}"`);
    if (!existsSync(join(MASTERS, `${clip}.wav`))) throw new Error(`no master for "${clip}"`);
    mkdirSync(out, { recursive: true });
    const master = masterOf(clip);
    writeFileSync(join(out, `${clip}-master-clean.wav`), wav(masterClip(master)));
    console.log(`${clip}-master-clean.wav`.padEnd(30), `${master.rate} Hz, the untouched recording`);
    for (const at of CRUSH_LEVELS) {
      writeFileSync(join(out, `${clip}-crush-${at}.wav`), wav(renderLine(line.who, master, at)));
      console.log(`${clip}-crush-${at}.wav`.padEnd(30), `${CRUSH[at].rate} Hz — ${CRUSH[at].notes}`);
    }
  }
}
