// Speaks a line in a cast member's voice (src/snes/audio/voice.mjs): the Kokoro take is recorded
// once into assets/voice/takes (the local Kokoro on 127.0.0.1:8936, or FINAL_NOTICE_KOKORO_URL),
// then digitized for the S-DSP and written as a 32 kHz WAV. A take already on disk is never re-asked.
//
//   node tools/voice.mjs <character> "<line>" <out.wav>
//   node tools/voice.mjs --sheet <dir>      every cast member saying their sample line
//   node tools/voice.mjs --cast             the cast and their settings
//   node tools/voice.mjs --partners [<dir>] bakes Ward and Mercer's fight lines (src/snes/barks.mjs)
//                                           into src/snes/audio/barks-brr.mjs, and writes <who>-barks.wav reels

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { castNames, digitize, parseWav, renderLine, takeSpeed, voiceOf } from '../src/snes/audio/voice.mjs';
import { DSP_HZ } from '../src/snes/audio/spc.mjs';
import { allLines } from '../src/snes/barks.mjs';
import { pack } from './snes-bank.mjs';
import { wav } from './snes-render.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const KOKORO = process.env.FINAL_NOTICE_KOKORO_URL ?? 'http://127.0.0.1:8936/speak';

export function takePath(who, text) {
  const v = voiceOf(who);
  const hash = createHash('sha1').update(`${v.voice}|${takeSpeed(v)}|${text}`).digest('hex').slice(0, 10);
  return join(ROOT, 'assets', 'voice', 'takes', `${v.voice}-${hash}.wav`);
}

export async function take(who, text) {
  const path = takePath(who, text);
  if (!existsSync(path)) {
    const v = voiceOf(who);
    const res = await fetch(KOKORO, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, voice: v.voice, speed: takeSpeed(v) }) });
    if (!res.ok) throw new Error(`Kokoro answered ${res.status} for ${who}`);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  }
  return parseWav(readFileSync(path));
}

// A brawl line as the game plays it: the BRR sample, the note that sounds it at the character's pitch
// and how many frames it lasts there.
export function bakeBark(who, takeData) {
  const v = voiceOf(who);
  const s = digitize(who, takeData);
  const midi = 60 + v.pitch;
  const frames = Math.ceil((s.pcm.length / (DSP_HZ * (261.6256 / s.rootHz) * 2 ** (v.pitch / 12))) * 60) + 2;
  return { midi, frames, rootHz: Number(s.rootHz.toFixed(4)), brr: pack(s.brr) };
}

async function bakeBarks(dir) {
  const rows = [];
  const reels = {};
  let bytes = 0;
  for (const line of allLines()) {
    const t = await take(line.who, line.text);
    const b = bakeBark(line.who, t);
    bytes += (b.brr.length * 3) / 4;
    rows.push(`  '${line.id}': { text: ${JSON.stringify(line.text)}, midi: ${b.midi}, frames: ${b.frames}, rootHz: ${b.rootHz}, brr: '${b.brr}' },`);
    if (dir) {
      const r = renderLine(line.who, t);
      writeFileSync(join(dir, `${line.id}.wav`), wav(r));
      (reels[line.who] ??= []).push(r);
    }
    console.log(line.id.padEnd(18), JSON.stringify(line.text), `${b.frames} frames`);
  }
  const head = '// Generated by tools/voice.mjs --partners from the Kokoro takes in assets/voice/takes, digitized in each\n// partner\'s cast voice. Each brr string is 9-byte BRR blocks: shift<<4 | filter<<2, then 16 nibbles.\n\nexport default {\n';
  writeFileSync(join(ROOT, 'src', 'snes', 'audio', 'barks-brr.mjs'), `${head}${rows.join('\n')}\n};\n`);
  for (const [who, parts] of Object.entries(reels)) {
    const gap = Math.round(DSP_HZ * 0.25);
    const len = parts.reduce((n, p) => n + p.left.length + gap, 0);
    const left = new Float32Array(len);
    const right = new Float32Array(len);
    let at = 0;
    for (const p of parts) {
      left.set(p.left, at);
      right.set(p.right, at);
      at += p.left.length + gap;
    }
    writeFileSync(join(dir, `${who}-barks.wav`), wav({ left, right, sampleRate: DSP_HZ }));
  }
  console.log('total', Math.round(bytes), 'B');
}

if (process.argv[1]?.endsWith('voice.mjs')) {
  const [first, ...rest] = process.argv.slice(2);
  if (first === '--cast') {
    for (const who of castNames()) {
      const { name, notes, sample, echo, fir, ...settings } = voiceOf(who);
      console.log(`${who}: ${name} (${notes}) ${JSON.stringify(settings)}`);
    }
  } else if (first === '--sheet') {
    mkdirSync(rest[0], { recursive: true });
    for (const who of castNames()) {
      const out = join(rest[0], `${who.replace(':', '-')}.wav`);
      writeFileSync(out, wav(renderLine(who, await take(who, voiceOf(who).sample))));
      console.log(out, JSON.stringify(voiceOf(who).sample));
    }
  } else if (first === '--partners') {
    if (rest[0]) mkdirSync(rest[0], { recursive: true });
    await bakeBarks(rest[0]);
  } else if (first && rest.length === 2) {
    writeFileSync(rest[1], wav(renderLine(first, await take(first, rest[0]))));
    console.log(rest[1]);
  } else {
    console.error(`usage: node tools/voice.mjs <character> "<line>" <out.wav> | --sheet <dir> | --cast | --partners [<dir>]\ncast: ${castNames().join(', ')}`);
    process.exit(1);
  }
}
